### ISSUE TITLE
Raumreservierung

### ISSUE THREAD

**Issue by InverseIntegral** [openhsr/hackathon-16#1]
Damit der Hackathon überhaupt durchgeführt werden kann, müssen wir einen entsprechenden Raum reservieren. Nach dem [Guide von MLH](https://guide.mlh.io/Organizer-Timeline/4-To-9-Months-Before/Venue.html) sind folgende Punkte wichtig für den Raum:
- Genug Platz für alle Teilnehmer
- WiFi (4 Geräte pro Teilnehmer) - Sollte kein Problem darstellen
- Stromversorgung
- Tische und Stühle für alle Teilnehmer
- Zugänglichkeit des Raumes - Auch dieser Punkt sollte kein Problem darstellen.

Die letzte LAN Party wurde laut @sfkeller beim Nordeingang des Gebäude 1 durchgeführt. Ein anderes Gebäude, das sich eventuell auch für die Durchführung des Events eignet, ist das Gebäude 5. Falls jemand von euch einen weitern Vorschlag hat, oder sich mit der Reservierung auskennt, meldet euch einfach.

**Comment by fabianhauser** [comment]
Soweit ich weiss, kann grundsätzlich mit der Unterstützung eines Dozenten ein Unterrichtsraum im Zeitrahmen von 07:00 - 20:00 reserviert werden. Zudem müssen die üblichen Raumnutzungsregeln (z.B. kein Essen) eingehalten werden.

Falls der Event ausserhalb dieses Rahmens stattfindet ([_Are you permitted to host an overnight event?_](https://guide.mlh.io/Organizer-Timeline/4-To-9-Months-Before/Venue.html#ask-about-venue-requirements-and-restrictions)), muss dafür einen Antrag an die Hochschuldienste gestellt werden (und damit bestimmte Auflagen erfüllen, z.B. Verantwortlichkeit/Haftung bei Schäden, Securitas, Reinigung etc.).

Hier würde es sich sicher lohnen, mal Kontakt mit der Fachschaft I aufzunehmen (die meines Wissens die LAN-Party organisiert und sicher ein paar gute Tipps auf Lager hat :wink:)
(Ein geeigneten Raum wäre übrigens auch der kleine Saal neben der Mensa?)

**Comment by InverseIntegral** [comment]
Danke für die Antwort. Ich werde mal zusammen mit @DennisLigtenberg einen Dozenten kontaktieren.

**Comment by sfkeller** [comment]
Ihr habt mich ja schon kontaktiert :-) Ich schlage vor, ihr sprecht bei Frau Ingrid Vettiger vor und fragt, was zu tun sei. Sie ist Assistentin des Verwaltungsdirektors und hilft bei der Bewilligung.

**Comment by InverseIntegral** [comment]
Der Raum ist reserviert und die Anmeldung ist geöffnet.
